networks:
  app-network:
    driver: bridge

services:
  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '${API_PORT:-3000}:${API_PORT:-3000}'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: node dist/main/api.js
    networks:
      - app-network
    volumes:
      - certificates-data:/app/certificates

  worker:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: node dist/main/worker.js
    networks:
      - app-network
    volumes:
      - certificates-data:/app/certificates

  prefeitura-mock:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '${MOCK_PORT:-3001}:${MOCK_PORT:-3001}'
    command: node dist/main/prefeitura-mock.js
    networks:
      - app-network

  redis:
    env_file:
      - .env
    image: redis:latest
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-password}
    ports:
      - '${REDIS_PORT:-6379}:${REDIS_PORT:-6379}'
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    volumes:
      - redis-data:/data

  postgres:
    env_file:
      - .env
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-app_db}
    ports:
      - '${DATABASE_PORT:-5432}:${DATABASE_PORT:-5432}'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USER}", "-h", "${DATABASE_HOST}"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  redis-data:
  certificates-data:
  postgres-data:
